"""empty message

Revision ID: 188b5564fd6b
Revises: dd8a03a30323
Create Date: 2020-02-12 23:30:02.115129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188b5564fd6b'
down_revision = 'dd8a03a30323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.add_column('doctor', sa.Column('lastname', sa.String(length=80), nullable=False))
    op.drop_column('doctor', 'age')
    op.add_column('paciente', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.add_column('paciente', sa.Column('lastname', sa.String(length=80), nullable=False))
    op.drop_column('paciente', 'age')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paciente', sa.Column('age', sa.DATE(), nullable=False))
    op.drop_column('paciente', 'lastname')
    op.drop_column('paciente', 'date_of_birth')
    op.add_column('doctor', sa.Column('age', sa.DATE(), nullable=False))
    op.drop_column('doctor', 'lastname')
    op.drop_column('doctor', 'date_of_birth')
    # ### end Alembic commands ###
