"""empty message

Revision ID: 1eec6a7e3c1d
Revises: 188b5564fd6b
Create Date: 2020-02-14 00:01:12.306153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1eec6a7e3c1d'
down_revision = '188b5564fd6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'doctor', ['phone'])
    op.create_unique_constraint(None, 'paciente', ['phone'])
    op.drop_constraint('tratamiento_ibfk_1', 'tratamiento', type_='foreignkey')
    op.drop_column('tratamiento', 'cita_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('cita_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('tratamiento_ibfk_1', 'tratamiento', 'cita', ['cita_id'], ['id'])
    op.drop_constraint(None, 'paciente', type_='unique')
    op.drop_constraint(None, 'doctor', type_='unique')
    # ### end Alembic commands ###
