"""empty message

Revision ID: 57b5d64d2289
Revises: c8f5a1bd1353
Create Date: 2020-02-11 23:31:36.219139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b5d64d2289'
down_revision = 'c8f5a1bd1353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tratamiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tratamiento_name', sa.String(length=125), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('cita_id', sa.Integer(), nullable=True),
    sa.Column('campo_falso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cita_id'], ['cita.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descripcion'),
    sa.UniqueConstraint('tratamiento_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tratamiento')
    # ### end Alembic commands ###
