"""empty message

Revision ID: 59ba2ce1f627
Revises: 932558296042
Create Date: 2020-02-19 23:15:49.585274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59ba2ce1f627'
down_revision = '932558296042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cita', sa.Column('planned_date', sa.Date(), nullable=False))
    op.drop_column('cita', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cita', sa.Column('date', sa.DATE(), nullable=False))
    op.drop_column('cita', 'planned_date')
    # ### end Alembic commands ###
