"""empty message

Revision ID: 932558296042
Revises: d03248ee0c57
Create Date: 2020-02-19 22:38:23.553646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '932558296042'
down_revision = 'd03248ee0c57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cita_ibfk_1', 'cita', type_='foreignkey')
    op.drop_column('cita', 'price_tot')
    op.drop_column('cita', 'doctor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cita', sa.Column('doctor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('cita', sa.Column('price_tot', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('cita_ibfk_1', 'cita', 'doctor', ['doctor_id'], ['id'])
    # ### end Alembic commands ###
