"""empty message

Revision ID: d03248ee0c57
Revises: c737b597ad66
Create Date: 2020-02-19 22:10:22.046839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03248ee0c57'
down_revision = 'c737b597ad66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('id_cita', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tratamiento', 'cita', ['id_cita'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tratamiento', type_='foreignkey')
    op.drop_column('tratamiento', 'id_cita')
    # ### end Alembic commands ###
