"""empty message

Revision ID: dd8a03a30323
Revises: 57b5d64d2289
Create Date: 2020-02-11 23:32:49.923602

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd8a03a30323'
down_revision = '57b5d64d2289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tratamiento', 'campo_falso')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('campo_falso', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
