"""empty message

Revision ID: f314acdf3a3b
Revises: 59ba2ce1f627
Create Date: 2020-02-19 23:20:49.706229

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f314acdf3a3b'
down_revision = '59ba2ce1f627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cita', sa.Column('tratamiento_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cita', 'tratamiento', ['tratamiento_id'], ['id'])
    op.drop_constraint('tratamiento_ibfk_1', 'tratamiento', type_='foreignkey')
    op.drop_column('tratamiento', 'id_cita')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tratamiento', sa.Column('id_cita', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('tratamiento_ibfk_1', 'tratamiento', 'cita', ['id_cita'], ['id'])
    op.drop_constraint(None, 'cita', type_='foreignkey')
    op.drop_column('cita', 'tratamiento_id')
    # ### end Alembic commands ###
